swagger: "2.0"
info:
  description: "yaml"
  version: "1.0.0"
  title: "Petstore API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /pet/{petId}:
    get:
      summary: "API"
      description: "pet API"
      oprationId: getPet
      parameters:
      - name: "petId"
        in: "path"
        description: "pet ID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "response"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "doggie"
    put:
      summary: "API"
      description: "pet API"
      oprationId: putPet
      parameters:
      - name: "petId"
        in: "path"
        description: "pet ID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "response"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "doggie"
  /pet/sample/{petId}:
    post:
      summary: "API"
      description: "pet API"
      oprationId: postPet
      parameters:
      - name: "petId"
        in: "path"
        description: "pet ID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "response"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "doggie"
  /human/sample/{humanId}:
    get:
      summary: "API"
      description: "human API"
      oprationId: getHuman
      parameters:
      - name: "humanId"
        in: "path"
        description: "human ID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "response"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "doggie"
  /machine/sample/{machineId}:
    get:
      summary: "API"
      description: "machine API"
      oprationId: getMachine
      parameters:
      - name: "machineId"
        in: "path"
        description: "machine ID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "response"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "doggie"
